.\" SPDX-License-Identifier: ISC
.Dd $Mdocdate$
.Dt TEMPLATE 1
.Os
.Sh NAME
.Nm template
.Nd template program
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Ar string
.Sh DESCRIPTION
The
.Nm
utility frobnicates an optional
.Ar string .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
Print usage and exit.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr tmpl_new 3
